name: flutter_ocr_sdk
description: A wrapper for Dynamsoft Capture Vision SDK, capable of recognizing MRZ (Machine Readable Zone) and VIN (Vehicle Identification Number).
version: 2.0.0
homepage: https://github.com/yushulx/flutter_ocr_sdk
repository: https://github.com/yushulx/flutter_ocr_sdk

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ^0.6.3
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dynamsoft.flutter_ocr_sdk
        pluginClass: FlutterOcrSdkPlugin
      ios:
        pluginClass: FlutterOcrSdkPlugin
      linux:
        pluginClass: FlutterOcrSdkPlugin
      windows:
        pluginClass: FlutterOcrSdkPluginCApi
      web: 
        pluginClass: FlutterOcrSdkWeb
        fileName: flutter_ocr_sdk_web.dart
