name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Get dependencies
      run: |
        cd example
        flutter pub get
    - uses: bluefireteam/flutter-gh-pages@v7
      with:
          baseHref: /flutter_ocr_sdk/
